version: '3.1'
services:
  discovery-service:
    image: user-group-service/discovery-service
    networks:
      - user-group-network

  user-service:
    image: user-group-service/users-service
    environment:
      DISCOVERY_URL: discovery-service
    networks:
      - user-group-network

  group-service:
    image: user-group-service/group-service
    environment:
      DISCOVERY_URL: discovery-service
    networks:
      - user-group-network

networks:
  user-group-network:
