version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: 1234
    image: sqshq/piggymetrics-config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: 1234
    image: sqshq/piggymetrics-registry
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: 1234
    image: sqshq/piggymetrics-gateway
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 1234
      ACCOUNT_SERVICE_PASSWORD: 1234
    image: sqshq/piggymetrics-auth-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 1234
      ACCOUNT_SERVICE_PASSWORD: 1234
    image: sqshq/piggymetrics-account-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"
