spring:
  application:
    name: group-service
  cloud:
    config:
      uri: http://config:8888
      fail-fast: true
      password: 1234
      username: user

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0