server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0